import type { Metadata } from 'next';

import Aside from '../components/Aside';
import Footer from '../components/Footer';
import { getAllArticlesMetadata } from '../../utils/mdx';
import ArticlePreview from '../components/ArticlePreview';

export const metadata: Metadata = {
  authors: [{ name: 'Marouane Faris' }],
  description: "Marouane Faris' Blog. Generated by create next app",
  openGraph: {
    type: 'website',
    url: 'https://www.marouanefaris.dev/',
    title: "Marouane Faris' personnal blog",
    description: "Marouane Faris' Blog. Made with Next JS",
    images: [
      {
        url: '/photo_linkedin.jpeg',
      },
    ],
  },
};

export default function Home() {
  const allArticlesMetaData = getAllArticlesMetadata();
  return (
    <>
      <Aside />
      <main>
        {allArticlesMetaData
          .sort((a, b) => {
            if (a.id > b.id) return -1;
            return 1;
          })
          .map((articleMetaData) => (
            <ArticlePreview
              key={articleMetaData.id}
              title={articleMetaData.title}
              readingTime={articleMetaData.readingTime}
              publicationDate={articleMetaData.date}
              description={articleMetaData.metaDesc}
              slug={articleMetaData.slug}
            />
          ))}
      </main>
      <Footer />
    </>
  );
}
