import { Merriweather } from '@next/font/google';
import ContextProvider from '../components/ContextProvider';
import '../styles/globals.css';
import '../styles/components/Toggle.css';
import Layout from '../components/Layout';
import { AppProps } from 'next/app';
import Head from 'next/head';

const font = Merriweather({ subsets: ['latin'], weight: '400' });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Marouane Faris</title>
        <meta name="author" content="Marouane Faris" />
        <meta
          name="description"
          content="Marouane Faris' Blog. Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
        <meta property="og:title" content="Marouane Faris' personnal blog" />
        <meta
          property="og:description"
          content="Marouane Faris' Blog. Made with Next JS"
        />
        <meta property="og:image" content="/photo_linkedin.jpeg" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <ContextProvider>
        <Layout>
          <>
            <style jsx global>{`
              html {
                font-family: ${font.style.fontFamily};
                font-weight: 400;
                word-wrap: break-word;
                font-kerning: normal;
              }
            `}</style>
            <Component {...pageProps} />
          </>
        </Layout>
      </ContextProvider>
    </>
  );
}
