import Head from 'next/head';
import Aside from '../components/Aside';
import Footer from '../components/Footer';
import { getAllArticles } from '../utils/mdx';
import ArticlePreview from '../components/ArticlePreview';

export function getStaticProps() {
  const allArticles = getAllArticles();
  return {
    props: { allArticles },
  };
}

export default function Home({ allArticles }) {
  return (
    <>
      <Head>
        <title>Marouane Faris</title>
        <meta name="author" content="Marouane Faris" />
        <meta
          name="description"
          content="Marouane Faris' Blog. Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <Aside />
      <main>
        {allArticles.map((article) => (
          <ArticlePreview
            key={article.id}
            title={article.title}
            readingTime={article.readingTime}
            publicationDate={article.date}
            description={article.metaDesc}
            slug={article.slug}
          />
        ))}
      </main>
      <Footer />
    </>
  );
}
