import Head from 'next/head';
import Aside from '../components/Aside';
import Footer from '../components/Footer';
import { IArticleMetadata, getAllArticlesMetadata } from '../utils/mdx';
import ArticlePreview from '../components/ArticlePreview';

export async function getStaticProps() {
  const allArticlesMetaData = await getAllArticlesMetadata();
  return {
    props: { allArticlesMetaData },
  };
}

export default function Home({
  allArticlesMetaData,
}: {
  allArticlesMetaData: IArticleMetadata[];
}) {
  return (
    <>
      <Head>
        <meta name="author" content="Marouane Faris" />
        <meta
          name="description"
          content="Marouane Faris' Blog. Generated by create next app"
        />
        <meta property="og:url" content="https://www.marouanefaris.dev/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Marouane Faris' personnal blog" />
        <meta
          property="og:description"
          content="Marouane Faris' Blog. Made with Next JS"
        />
        <meta property="og:image" content="/photo_linkedin.jpeg" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <Aside />
      <main>
        {allArticlesMetaData
          .sort((a, b) => {
            if (a.articleContentId > b.articleContentId) return -1;
            return 1;
          })
          .map((articleMetaData) => (
            <ArticlePreview
              key={articleMetaData.id}
              title={articleMetaData.title}
              readingTime={articleMetaData.readingTime}
              publicationDate={articleMetaData.date}
              description={articleMetaData.metaDesc}
              slug={articleMetaData.articleContentId}
            />
          ))}
      </main>
      <Footer />
    </>
  );
}
