import Head from 'next/head';
import Aside from '../components/Aside';
import Footer from '../components/Footer';
import { IArticleMetaData, getAllArticlesMetadata } from '../utils/mdx';
import ArticlePreview from '../components/ArticlePreview';

export function getStaticProps() {
  const allArticlesMetaData = getAllArticlesMetadata();
  return {
    props: { allArticlesMetaData },
  };
}

export default function Home({
  allArticlesMetaData,
}: {
  allArticlesMetaData: IArticleMetaData[];
}) {
  return (
    <>
      <Head>
        <title>Marouane Faris</title>
        <meta name="author" content="Marouane Faris" />
        <meta
          name="description"
          content="Marouane Faris' Blog. Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
        <meta property="og:title" content="Marouane Faris' personnal blog" />
        <meta
          property="og:description"
          content="Marouane Faris' Blog. Made with Next JS"
        />
        <meta property="og:image" content="/photo_linkedin.jpeg" />
        <link rel="icon" href="/favicon.png" type="image/png" />
      </Head>
      <Aside />
      <main>
        {allArticlesMetaData
          .sort((a, b) => {
            if (a.id < b.id) return -1;
            return 1;
          })
          .map((articleMetaData) => (
            <ArticlePreview
              key={articleMetaData.id}
              title={articleMetaData.title}
              readingTime={articleMetaData.readingTime}
              publicationDate={articleMetaData.date}
              description={articleMetaData.metaDesc}
              slug={articleMetaData.slug}
            />
          ))}
      </main>
      <Footer />
    </>
  );
}
